export const dataProperties = [
  {
    id: 1,
    location: "Ramos Mejía, BA",
    price: 200000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie1.jpeg",
    star: 4.5,
    meters: 430,
    description:
      "En el centro de la ciudad, ideal para quienes quieran tener toda la zona turística cerca y poder disfrutar de la comodidad de la vivienda.",
  },
  {
    id: 2,
    location: "José C. Paz, BA",
    price: 150000,
    bedrooms: 2,
    bathroom: 2,
    image: "propertie2.jpeg",
    star: 4,
    meters: 230,
    description:
      "En el centro de la ciudad, ideal para quienes quieran tener toda la zona turística cerca y poder disfrutar de la comodidad de la vivienda.",
  },
  {
    id: 3,
    location: "Ramos Mejía, BA",
    price: 35.0,
    bedrooms: 5,
    bathroom: 2,
    image: "propertie3.jpeg",
    star: 5,
    meters: 90,
    description:
      "En el centro de la ciudad, ideal para quienes quieran tener toda la zona turística cerca y poder disfrutar de la comodidad de la vivienda.",
  },
  {
    id: 4,
    location: "Pilar, BA",
    price: 200000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie4.jpeg",
    star: 4.2,
    meters: 120,
    description:
      "En el centro de la ciudad, ideal para quienes quieran tener toda la zona turística cerca y poder disfrutar de la comodidad de la vivienda.",
  },
  {
    id: 5,
    location: "Cuartel V, BA",
    price: 200000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie5.jpeg",
    star: 4.1,
    meters: 87,
    description:
      "En el centro de la ciudad, ideal para quienes quieran tener toda la zona turística cerca y poder disfrutar de la comodidad de la vivienda.",
  },
  {
    id: 6,
    location: "Ramos Mejía, BA",
    price: 200000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie6.jpeg",
    star: 3.7,
    meters: 220,
    description:
      "En el centro de la ciudad, ideal para quienes quieran tener toda la zona turística cerca y poder disfrutar de la comodidad de la vivienda.",
  },
  {
    id: 7,
    location: "Cuartel V, BA",
    price: 200000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie7.jpeg",
    star: 4.5,
    meters: 430,
    description:
      "En el centro de la ciudad, ideal para quienes quieran tener toda la zona turística cerca y poder disfrutar de la comodidad de la vivienda.",
  },
  {
    id: 8,
    location: "Pilar, BA",
    price: 200000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie8.jpeg",
    star: 4.5,
    meters: 330,
    description:
      "En el centro de la ciudad, ideal para quienes quieran tener toda la zona turística cerca y poder disfrutar de la comodidad de la vivienda.",
  },
  {
    id: 9,
    location: "Pilar, BA",
    price: 200000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie9.jpeg",
    star: 4.5,
    meters: 380,
    description:
      "En el centro de la ciudad, ideal para quienes quieran tener toda la zona turística cerca y poder disfrutar de la comodidad de la vivienda.",
  },
  {
    id: 10,
    location: "Cuartel V, BA",
    price: 200000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie10.jpeg",
    star: 4.1,
    meters: 270,
    description:
      "En el centro de la ciudad, ideal para quienes quieran tener toda la zona turística cerca y poder disfrutar de la comodidad de la vivienda.",
  },
  {
    id: 11,
    location: "Pilar, BA",
    price: 200000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie11.jpeg",
    star: 5,
    meters: 430,
    description:
      "En el centro de la ciudad, ideal para quienes quieran tener toda la zona turística cerca y poder disfrutar de la comodidad de la vivienda.",
  },
  {
    id: 12,
    location: "Pilar, BA",
    price: 200000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie12.jpeg",
    star: 3.9,
    meters: 76,
    description:
      "En el centro de la ciudad, ideal para quienes quieran tener toda la zona turística cerca y poder disfrutar de la comodidad de la vivienda.",
  },
  {
    id: 13,
    location: "José C. Paz, BA",
    price: 200000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie13.jpeg",
    star: 4.8,
    meters: 290,
    description:
      "En el centro de la ciudad, ideal para quienes quieran tener toda la zona turística cerca y poder disfrutar de la comodidad de la vivienda.",
  },
  {
    id: 14,
    location: "Pilar, BA",
    price: 200000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie14.jpeg",
    star: 4.9,
    meters: 180,
    description:
      "En el centro de la ciudad, ideal para quienes quieran tener toda la zona turística cerca y poder disfrutar de la comodidad de la vivienda.",
  },
  {
    id: 15,
    location: "Ramos Mejía, BA",
    price: 200000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie15.jpeg",
    star: 4.1,
    meters: 287,
    description:
      "En el centro de la ciudad, ideal para quienes quieran tener toda la zona turística cerca y poder disfrutar de la comodidad de la vivienda.",
  },
  {
    id: 16,
    location: "Nordeltus, BA",
    price: 200000,
    bedrooms: 3,
    bathroom: 1,
    image: "propertie16.jpeg",
    star: 4,
    meters: 290,
    description:
      "En el centro de la ciudad, ideal para quienes quieran tener toda la zona turística cerca y poder disfrutar de la comodidad de la vivienda.",
  },
];
